apiVersion: v1
kind: Service
metadata:
  name: web-static
  labels:
    app.kubernetes.io/name: web-static
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-static
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
