#!/usr/bin/env bash
#
# Deploy CampusConsult to Azure App Service for Containers.
#
#   ./deploy/azure/deploy.sh            full deploy (safe to re-run)
#   ./deploy/azure/deploy.sh app        rebuild + redeploy the app only
#   ./deploy/azure/deploy.sh settings   push app settings from backend/.env
#   ./deploy/azure/deploy.sh logs       tail live container logs
#   ./deploy/azure/deploy.sh info       print URLs and connection strings
#   ./deploy/azure/deploy.sh destroy    delete the whole resource group
#
# Every step is idempotent — re-running skips what already exists.
#
# Architecture:
#   Azure Container Registry  →  builds the image IN Azure (see note below)
#   App Service (Linux, B1)   →  runs Dockerfile.monolith, public HTTPS URL
#   PostgreSQL Flexible Srv   →  managed database, survives redeploys
#
# NOTE ON ARCHITECTURE: `az acr build` runs the Docker build on Azure's own
# amd64 agents. Building locally on an Apple Silicon Mac produces an arm64
# image that App Service cannot run — it starts and dies with no useful error.
# This is why the script never uses local `docker build`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE="$ROOT/deploy/azure/.env.azure"
ENV_FILE="$ROOT/backend/.env"

LOCATION="${LOCATION:-germanywestcentral}"
# Postgres Flexible Server is capacity-restricted in some regions on trial and
# student subscriptions ("The location is restricted from performing this
# operation"). Try candidates in order and keep whichever succeeds.
PG_LOCATION_CANDIDATES="${PG_LOCATION:-} ${LOCATION} westeurope northeurope swedencentral francecentral uksouth eastus"
PLAN_SKU="${PLAN_SKU:-B1}"          # B1 = 1.75GB. Bump to B2 if the app OOMs.
PG_SKU="${PG_SKU:-Standard_B1ms}"
PG_TIER="${PG_TIER:-Burstable}"
PG_STORAGE="${PG_STORAGE:-32}"
PG_VERSION="${PG_VERSION:-16}"
PG_DB="uniadvisor_db"
PG_ADMIN="uniadvisor"

if [ -t 1 ]; then
  C0=$'\033[0m'; CB=$'\033[1m'; CG=$'\033[32m'; CY=$'\033[33m'; CR=$'\033[31m'; CC=$'\033[36m'
else C0=""; CB=""; CG=""; CY=""; CR=""; CC=""; fi
step() { printf "%s==>%s %s\n" "$CC$CB" "$C0$CB" "$1$C0"; }
ok()   { printf "  %s✓%s %s\n" "$CG" "$C0" "$1"; }
warn() { printf "  %s!%s %s\n" "$CY" "$C0" "$1"; }
die()  { printf "  %s✗%s %s\n" "$CR" "$C0" "$1" >&2; exit 1; }

# ── read a value out of backend/.env (handles quotes) ────────────
getenv() {
  python3 - "$ENV_FILE" "$1" <<'PY'
import sys, re
path, key = sys.argv[1], sys.argv[2]
try:
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if k.strip() == key:
            print(v.strip().strip('"').strip("'"))
            break
except FileNotFoundError:
    pass
PY
}

# ── names: globally-unique, generated once and remembered ────────
init_state() {
  if [ -f "$STATE" ]; then
    # shellcheck disable=SC1090
    . "$STATE"
    return
  fi
  step "First run — generating resource names"
  # Generated with python, not `tr </dev/urandom | head`: head closes the pipe,
  # tr dies with SIGPIPE (141), and under `set -o pipefail` that aborts the
  # whole script silently.
  local sfx pgpw
  sfx="$(python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_lowercase+string.digits) for _ in range(6)))")"
  pgpw="$(python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_letters+string.digits) for _ in range(28)))")"

  cat > "$STATE" <<EOF
# Generated by deploy.sh — gitignored. Keep this file; it identifies your resources.
RG="campusconsult-rg"
ACR="ccacr${sfx}"
APP="campusconsult-${sfx}"
PLAN="campusconsult-plan"
PG="campusconsult-pg-${sfx}"
PG_PASSWORD="${pgpw}"
LOCATION="${LOCATION}"
EOF
  chmod 600 "$STATE"
  # shellcheck disable=SC1090
  . "$STATE"
  ok "names saved to deploy/azure/.env.azure (gitignored)"
}

preflight() {
  step "Checking prerequisites"
  command -v az >/dev/null 2>&1 || die "azure-cli not found — brew install azure-cli"
  az account show >/dev/null 2>&1 || die "not logged in — run: az login"
  local sub
  sub="$(az account show --query name -o tsv)"
  ok "az CLI, subscription: $sub"
  [ -f "$ENV_FILE" ] || die "backend/.env missing — its keys are copied into App Service settings"
  ok "backend/.env"
  [ -f "$ROOT/Dockerfile.monolith" ] || die "Dockerfile.monolith missing"
  ok "Dockerfile.monolith"
}

create_rg() {
  step "Resource group"
  if az group show -n "$RG" >/dev/null 2>&1; then ok "$RG exists"
  else az group create -n "$RG" -l "$LOCATION" -o none && ok "created $RG in $LOCATION"; fi
}

create_acr() {
  step "Container registry"
  if az acr show -n "$ACR" -g "$RG" >/dev/null 2>&1; then ok "$ACR exists"
  else
    az acr create -n "$ACR" -g "$RG" --sku Basic --admin-enabled true -o none
    ok "created $ACR"
  fi
}

build_image() {
  step "Building image in Azure (amd64)"
  warn "this takes 5–10 min on the first run — npm ci + pip install happen remotely"
  az acr build \
    --registry "$ACR" \
    --image "campusconsult:latest" \
    --file "$ROOT/Dockerfile.monolith" \
    "$ROOT" \
    --only-show-errors
  ok "image pushed: $ACR.azurecr.io/campusconsult:latest"
}

create_pg() {
  step "PostgreSQL flexible server"

  if az postgres flexible-server show -n "$PG" -g "$RG" >/dev/null 2>&1; then
    ok "$PG exists"
    PG_LOCATION="$(az postgres flexible-server show -n "$PG" -g "$RG" --query location -o tsv)"
  else
    warn "provisioning Postgres — usually 3–5 minutes per attempt"
    local created="" errfile
    errfile="$(mktemp)"

    for region in $PG_LOCATION_CANDIDATES; do
      [ -n "$region" ] || continue
      printf "  trying %s ... " "$region"
      if az postgres flexible-server create \
          --name "$PG" --resource-group "$RG" --location "$region" \
          --admin-user "$PG_ADMIN" --admin-password "$PG_PASSWORD" \
          --sku-name "$PG_SKU" --tier "$PG_TIER" \
          --storage-size "$PG_STORAGE" --version "$PG_VERSION" \
          --public-access 0.0.0.0 \
          --yes -o none 2>"$errfile"; then
        printf "%sok%s\n" "$CG" "$C0"
        created="$region"
        break
      fi
      if grep -qi "restricted\|not available\|NotAvailable\|quota" "$errfile"; then
        printf "%srestricted%s\n" "$CY" "$C0"
      else
        printf "%sfailed%s\n" "$CR" "$C0"
        sed 's/^/      /' "$errfile" | head -4
      fi
    done
    rm -f "$errfile"

    [ -n "$created" ] || die "no candidate region accepted a Postgres server. Try: PG_LOCATION=<region> ./deploy/azure/deploy.sh"
    PG_LOCATION="$created"
    ok "created $PG in $PG_LOCATION"

    # Remember it so re-runs and the app land in the same place
    if grep -q '^PG_LOCATION=' "$STATE" 2>/dev/null; then
      python3 - "$STATE" "$PG_LOCATION" <<'PYEOF'
import re, sys
p, loc = sys.argv[1], sys.argv[2]
s = open(p).read()
open(p, "w").write(re.sub(r'^PG_LOCATION=.*$', f'PG_LOCATION="{loc}"', s, flags=re.M))
PYEOF
    else
      printf 'PG_LOCATION="%s"\n' "$PG_LOCATION" >> "$STATE"
    fi
  fi

  az postgres flexible-server db create \
    -g "$RG" -s "$PG" -d "$PG_DB" -o none 2>/dev/null || true
  ok "database $PG_DB ready"

  # The app cannot reach the database without this rule, so do NOT swallow a
  # failure here — a silent miss shows up much later as a 503 with a confusing
  # "is the server running on that host" error in the container log.
  if az postgres flexible-server firewall-rule create \
      -g "$RG" -s "$PG" --rule-name AllowAzureServices \
      --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 -o none 2>/dev/null; then
    ok "Azure services allowed through the Postgres firewall"
  else
    if az postgres flexible-server firewall-rule show \
        -g "$RG" -s "$PG" --rule-name AllowAzureServices >/dev/null 2>&1; then
      ok "Azure services rule already present"
    else
      die "could not create the AllowAzureServices firewall rule — the app will not reach Postgres"
    fi
  fi

  local myip
  myip="$(curl -s https://api.ipify.org || true)"
  if [ -n "$myip" ]; then
    if az postgres flexible-server firewall-rule create \
      -g "$RG" -s "$PG" --rule-name "dev-$(echo "$myip" | tr '.' '-')" \
      --start-ip-address "$myip" --end-ip-address "$myip" -o none 2>/dev/null; then
      ok "firewall opened for your IP ($myip)"
    else
      warn "could not add a rule for $myip — the seed scripts may not reach the DB"
    fi
  else
    warn "could not detect your public IP — add a firewall rule manually to run the seeders"
  fi
}

db_url() {
  # Flexible Server requires TLS; psycopg2 needs it stated explicitly.
  echo "postgresql://${PG_ADMIN}:${PG_PASSWORD}@${PG}.postgres.database.azure.com:5432/${PG_DB}?sslmode=require"
}

create_webapp() {
  step "App Service"
  if ! az appservice plan show -n "$PLAN" -g "$RG" >/dev/null 2>&1; then
    az appservice plan create -n "$PLAN" -g "$RG" --is-linux --sku "$PLAN_SKU" \
      --location "${PG_LOCATION:-$LOCATION}" -o none
    ok "created plan $PLAN ($PLAN_SKU) in ${PG_LOCATION:-$LOCATION}"
  else ok "plan $PLAN exists"; fi

  local acr_pw
  acr_pw="$(az acr credential show -n "$ACR" --query 'passwords[0].value' -o tsv)"

  if ! az webapp show -n "$APP" -g "$RG" >/dev/null 2>&1; then
    az webapp create -n "$APP" -g "$RG" -p "$PLAN" \
      --deployment-container-image-name "$ACR.azurecr.io/campusconsult:latest" -o none
    ok "created web app $APP"
  else ok "web app $APP exists"; fi

  az webapp config container set -n "$APP" -g "$RG" \
    --docker-custom-image-name "$ACR.azurecr.io/campusconsult:latest" \
    --docker-registry-server-url "https://$ACR.azurecr.io" \
    --docker-registry-server-user "$ACR" \
    --docker-registry-server-password "$acr_pw" -o none
  ok "container configured"
}

push_settings() {
  step "App settings"
  local url="https://${APP}.azurewebsites.net"

  # Secrets come from backend/.env so nothing sensitive lives in this script
  local secret_key admin_email admin_pw
  secret_key="$(getenv SECRET_KEY)"
  admin_email="$(getenv ADMIN_EMAIL)"
  admin_pw="$(getenv ADMIN_PASSWORD)"
  [ -n "$secret_key" ] || die "SECRET_KEY missing from backend/.env"

  local -a settings=(
    "DATABASE_URL=$(db_url)"
    "SECRET_KEY=${secret_key}"
    "DEBUG=False"
    "FRONTEND_URL=${url}"
    "CORS_ORIGINS=[\"${url}\"]"
    "ADMIN_EMAIL=${admin_email}"
    "ADMIN_PASSWORD=${admin_pw}"

    # /home is the only persistent path in an App Service container, and it
    # needs this flag switched on. ChromaDB lives there so the vector index
    # survives restarts instead of re-embedding through Azure OpenAI each time.
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE=true"
    "CHROMA_DB_PATH=/home/chroma_db"

    # nginx in the image listens on 80; tell App Service where to route.
    "WEBSITES_PORT=80"
    # The image is large and startup pulls it — default 230s is not enough.
    "WEBSITES_CONTAINER_START_TIME_LIMIT=600"

    "AZURE_OPENAI_ENDPOINT=$(getenv AZURE_OPENAI_ENDPOINT)"
    "AZURE_OPENAI_API_KEY=$(getenv AZURE_OPENAI_API_KEY)"
    "AZURE_OPENAI_DEPLOYMENT=$(getenv AZURE_OPENAI_DEPLOYMENT)"
    "AZURE_OPENAI_API_VERSION=$(getenv AZURE_OPENAI_API_VERSION)"
    "AZURE_EMBEDDING_ENDPOINT=$(getenv AZURE_EMBEDDING_ENDPOINT)"
    "AZURE_EMBEDDING_API_KEY=$(getenv AZURE_EMBEDDING_API_KEY)"
    "AZURE_EMBEDDING_DEPLOYMENT=$(getenv AZURE_EMBEDDING_DEPLOYMENT)"
    "AZURE_EMBEDDING_API_VERSION=$(getenv AZURE_EMBEDDING_API_VERSION)"

    "SMTP_HOST=$(getenv SMTP_HOST)"
    "SMTP_PORT=$(getenv SMTP_PORT)"
    "SMTP_USER=$(getenv SMTP_USER)"
    "SMTP_PASSWORD=$(getenv SMTP_PASSWORD)"
    "SMTP_FROM_EMAIL=$(getenv SMTP_FROM_EMAIL)"
  )

  az webapp config appsettings set -n "$APP" -g "$RG" --settings "${settings[@]}" -o none
  ok "$(( ${#settings[@]} )) settings applied"

  az webapp log config -n "$APP" -g "$RG" \
    --docker-container-logging filesystem --level information -o none 2>/dev/null || true
  ok "container logging enabled"
}

show_info() {
  local url="https://${APP}.azurewebsites.net"
  printf "\n"
  printf "  %sCampusConsult on Azure%s\n\n" "$CG$CB" "$C0"
  printf "    App        %s%s%s\n" "$CB" "$url" "$C0"
  printf "    API docs   %s%s/docs%s\n" "$CB" "$url" "$C0"
  printf "    Registry   %s.azurecr.io\n" "$ACR"
  printf "    Postgres   %s.postgres.database.azure.com\n" "$PG"
  printf "    Group      %s\n" "$RG"
  printf "    Regions    app+db: %s · registry: %s\n\n" "${PG_LOCATION:-$LOCATION}" "$LOCATION"
  printf "  Seed the database from this machine:\n\n"
  printf "    cd backend && source venv/bin/activate\n"
  printf "    export AZ_DB='%s'\n" "$(db_url)"
  printf "    python -m scripts.seed_programs_heroku --file data/program_details.json --db-url \"\$AZ_DB\"\n"
  printf "    python -m scripts.create_admin --email %s --password '<pick-a-strong-one>' --db-url \"\$AZ_DB\"\n" "${admin_email:-admin@daad.de}"
  printf "    python -m scripts.seed_community --db-url \"\$AZ_DB\"\n\n"
}

case "${1:-all}" in
  all)
    preflight; init_state; create_rg; create_acr; create_pg; build_image; create_webapp; push_settings
    step "Restarting"
    az webapp restart -n "$APP" -g "$RG" -o none
    ok "deployed"
    show_info
    ;;
  app)
    preflight; init_state; build_image; create_webapp
    az webapp restart -n "$APP" -g "$RG" -o none
    ok "redeployed"; show_info ;;
  settings)  preflight; init_state; push_settings; az webapp restart -n "$APP" -g "$RG" -o none; ok "settings pushed" ;;
  logs)      init_state; az webapp log tail -n "$APP" -g "$RG" ;;
  doctor)
    init_state
    step "Postgres"
    az postgres flexible-server show -g "$RG" -n "$PG" \
      --query "{state:state, publicAccess:network.publicNetworkAccess, fqdn:fullyQualifiedDomainName, location:location}" -o yaml
    step "Firewall rules"
    az postgres flexible-server firewall-rule list -g "$RG" -s "$PG" -o table
    step "App settings (DATABASE_URL host only)"
    az webapp config appsettings list -n "$APP" -g "$RG" \
      --query "[?name=='DATABASE_URL'].value" -o tsv | sed -E 's#//[^@]+@#//***:***@#'
    step "Container state"
    az webapp show -n "$APP" -g "$RG" --query "{state:state, availability:availabilityState}" -o yaml
    ;;
  info)      init_state; admin_email="$(getenv ADMIN_EMAIL)"; show_info ;;
  destroy)
    init_state
    printf "%sThis deletes resource group %s and everything in it.%s Type the app name to confirm: " "$CR$CB" "$RG" "$C0"
    read -r answer
    [ "$answer" = "$APP" ] || { echo "Aborted."; exit 0; }
    az group delete -n "$RG" --yes --no-wait
    ok "deletion started" ;;
  *) sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
